name: Build and Upload Portable App Release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release_cli_portable:
    strategy:
      matrix:
        rid: [linux-arm64, linux-musl-arm64, linux-x64, linux-musl-x64, osx-x64, osx-arm64, win-x64, win-x86, win-arm64]
        build_configuration: [Release]
        deploy_mode: [with-runtime, no-runtime]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Build App
        run: |
          if [ "${{ matrix.deploy_mode }}" == "with-runtime" ]; then
            dotnet publish -c ${{ matrix.build_configuration }} -r ${{ matrix.rid }} SJTUGeek.MCP.Server/SJTUGeek.MCP.Server.csproj --self-contained
          else
            dotnet publish -c ${{ matrix.build_configuration }} -r ${{ matrix.rid }} SJTUGeek.MCP.Server/SJTUGeek.MCP.Server.csproj
          fi

      - name: Copy Python Dependency
        run: cp SJTUGeek.MCP.Scripts/requirements.txt SJTUGeek.MCP.Server/bin/${{ matrix.build_configuration }}/net9.0/${{ matrix.rid }}/publish/requirements.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SJTUGeek.MCP.Server-${{ matrix.rid }}-${{ matrix.build_configuration }}-${{ matrix.deploy_mode }}
          path: SJTUGeek.MCP.Server/bin/${{ matrix.build_configuration }}/net9.0/${{ matrix.rid }}/publish/

      - name: Pack Release Asset
        run: |
          cd SJTUGeek.MCP.Server/bin/${{ matrix.build_configuration }}/net9.0/${{ matrix.rid }}/publish/
          zip -r /tmp/app-${{ matrix.rid }}-${{ matrix.build_configuration }}.zip .

      - name: Get the Latest Release Info
        id: latest_release_info
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: /tmp/app-${{ matrix.rid }}-${{ matrix.build_configuration }}.zip
          asset_name: SJTUGeek.MCP.Server-${{ matrix.rid }}-${{ matrix.deploy_mode }}.zip
          asset_content_type: application/zip
